[package]
name = "qipi"
description = "ğŸ¦‰ The blazing-fast, disk-efficient package manager."
authors = ["NehuÃ©n <https://github.com/nehu3n>"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
